var totalColors = [{ two:true,five:false, twoBasic: true, fiveBasic: false, rgb: [255, 255, 255], id: "C-1", name: "White" },
{ two:true,five:false, twoBasic: true, fiveBasic: false, rgb: [0, 0, 0], id: "C-2", name: "Black" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [246, 176, 76], id: "C-3", name: "Tangerine" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [237, 139, 0], id: "C-4", name: "Yellow Orange" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [225, 6, 0], id: "C-5", name: "Tall Poppy" },
{ two:true,five:false, twoBasic: true, fiveBasic: false, rgb: [186, 12, 52], id: "C-6", name: "Red" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [241, 167, 220], id: "C-7", name: "Carnation Pink" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [255, 52, 179], id: "C-8", name: "Hot Pink" },
{ two:true,five:false, twoBasic: true, fiveBasic: false, rgb: [219, 33, 82], id: "C-9", name: "Magenta" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [242, 240, 161], id: "C-10", name: "Picasso" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [255, 209, 0], id: "C-11", name: "Yellow" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [173, 220, 145], id: "C-12", name: "Pistachio" },
{ two:true,five:false, twoBasic: true, fiveBasic: false, rgb: [135, 216, 57], id: "C-13", name: "Pastel Green" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [36, 158, 107], id: "C-14", name: "Green" },
{ two:true,five:false, twoBasic: true, fiveBasic: false, rgb: [0, 124, 88], id: "C-15", name: "Green Tea" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [255, 255, 255], id: "C-16", name: "Bright Carrot" },
{ two:true,five:false, twoBasic: true, fiveBasic: false, rgb: [255, 103, 31], id: "C-17", name: "Orange" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [170, 220, 235], id: "C-18", name: "Sky Blue" },
{ two:true,five:false, twoBasic: true, fiveBasic: false, rgb: [65, 182, 230], id: "C-19", name: "Baby Blue" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [0, 144, 218], id: "C-20", name: "Light Blue" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [0, 51, 153], id: "C-21", name: "Dark Blue" },
{ two:true,five:false, twoBasic: true, fiveBasic: false, rgb: [252, 191, 169], id: "C-22", name: "Bubble Gum" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [204, 153, 102], id: "C-23", name: "Sand" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [255, 231, 128], id: "C-24", name: "Beeswax" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [167, 123, 202], id: "C-25", name: "Lavander" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [160, 94, 181], id: "C-26", name: "Pastel Lavender" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [51, 0, 114], id: "C-27", name: "Purple" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [180, 126, 0], id: "C-28", name: "Marigold" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [164, 73, 61], id: "C-29", name: "Bucaneer" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [122, 62, 44], id: "C-30", name: "Redwood" },
{ two:true,five:false, twoBasic: true, fiveBasic: false, rgb: [123, 77, 53], id: "C-31", name: "Light Brown" },
{ two:true,five:false, twoBasic: true, fiveBasic: false, rgb: [92, 71, 56], id: "C-32", name: "Brown" },
{ two:true,five:false, twoBasic: true, fiveBasic: false, rgb: [155, 155, 155], id: "C-33", name: "Gray 2" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [118, 119, 119], id: "C-34", name: "Gray 3" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [160, 159, 157], id: "C-35", name: "Silver" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [201, 128, 158], id: "C-36", name: "Old Pink" },
{ two:true,five:false, twoBasic: true, fiveBasic: false, rgb: [20, 123, 209], id: "C-37", name: "True Blue" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [105, 179, 231], id: "C-38", name: "Blue Enchantress" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [153, 214, 234], id: "C-39", name: "Shadow Blue" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [206, 220, 0], id: "C-40", name: "Key Lemon Pie" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [246, 235, 97], id: "C-41", name: "Pastel Yellow" },
{ two:true,five:false, twoBasic: true, fiveBasic: false, rgb: [250, 224, 83], id: "C-42", name: "Sandstone" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [165, 0, 52], id: "C-43", name: "Paprika" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [255, 163, 139], id: "C-44", name: "Burning Sand" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [93, 219, 93], id: "C-45", name: "Spring Green" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [243, 234, 93], id: "C-46", name: "Canary" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [243, 207, 179], id: "C-47", name: "Vainilla" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [255, 199, 44], id: "C-48", name: "Corn" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [236, 134, 208], id: "C-49", name: "Raspberry Pink" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [197, 180, 227], id: "C-50", name: "Maverick" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [252, 251, 205], id: "C-51", name: "Spring Sun" },
{ two:true,five:false, twoBasic: true, fiveBasic: false, rgb: [74, 31, 135], id: "C-52", name: "Royal Purple" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [115, 211, 60], id: "C-53", name: "Bright Green" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [0, 178, 169], id: "C-54", name: "Medium Turquoise" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [108, 194, 74], id: "C-55", name: "Conifer" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [136, 139, 141], id: "C-56", name: "Oslo Gray" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [188, 4, 35], id: "C-57", name: "Fresh Red" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [5, 8, 73], id: "C-58", name: "Black Rock" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [83, 26, 35], id: "C-59", name: "Scarlett" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [158, 229, 176], id: "C-60", name: "Sea Mist" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [241, 235, 156], id: "C-61", name: "Feta" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [241, 235, 156], id: "C-62", name: "Carnation" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [234, 190, 219], id: "C-63", name: "Lily Pink" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [165, 0, 80], id: "C-64", name: "Rose" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [239, 129, 46], id: "C-65", name: "Mango" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [252, 108, 133], id: "C-66", name: "Wild Watermelon" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [177, 78, 181], id: "C-67", name: "Orchid" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [105, 194, 238], id: "C-68", name: "Thootpaste Blue" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [45, 40, 43], id: "C-69", name: "Mine Shaft" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [24, 48, 40], id: "C-70", name: "Dark Green" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [234, 170, 0], id: "C-71", name: "Goldenrod" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [255, 197, 110], id: "C-72", name: "Pastel Orange" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [184, 97, 37], id: "C-73", name: "Siena" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [205, 178, 119], id: "C-74", name: "Deer" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [181, 129, 80], id: "C-75", name: "Clay" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [255, 109, 106], id: "C-76", name: "Coral Red" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [170, 87, 97], id: "C-77", name: "Deep Chestnut" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [92, 19, 27], id: "C-78", name: "Red Wine" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [89, 213, 216], id: "C-79", name: "Light Sea Blue" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [0, 174, 199], id: "C-80", name: "Sea Blue" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [72, 169, 197], id: "C-81", name: "Steel Blue" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [0, 174, 214], id: "C-82", name: "Azure" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [0, 133, 173], id: "C-83", name: "Dark Steel Blue" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [155, 188, 17], id: "C-84", name: "Drark Algae" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [153, 155, 48], id: "C-85", name: "Dark Olive" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [0, 133, 34], id: "C-86", name: "Jade Green" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [239, 239, 239], id: "C-87", name: "Ghost White" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [209, 209, 209], id: "C-88", name: "Ash Gray" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [187, 188, 188], id: "C-89", name: "Gray 1" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [72, 73, 85], id: "C-90", name: "Gray 4" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [21, 185, 71], id: "C-91", name: "Light Yellow 2" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [218, 182, 152], id: "C-92", name: "Sand 2" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [244, 169, 153], id: "C-93", name: "Coral Red 2" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [238, 125, 103], id: "C-94", name: "Coral Red 3" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [240, 134, 97], id: "C-95", name: "Coral Red 4" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [212, 114, 42], id: "C-96", name: "Orange 2" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [100, 172, 223], id: "C-97", name: "Light Blue 1" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [100, 194, 220], id: "C-98", name: "Light Blue 2" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [79, 159, 179], id: "C-99", name: "Light Blue 3" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [49, 150, 221], id: "C-100", name: "Blue 1" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [27, 108, 182], id: "C-101", name: "Blue 2" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [8, 57, 128], id: "C-102", name: "Blue 3" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [10, 102, 139], id: "C-103", name: "Blue 4" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [85, 91, 110], id: "C-104", name: "Blue 5" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [0, 78, 120], id: "C-105", name: "Blue 6" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [0, 85, 116], id: "C-106", name: "Blue 7" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [204, 190, 128], id: "C-107", name: "Light Green 1" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [164, 147, 80], id: "C-108", name: "Light Green 2" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [158, 136, 60], id: "C-109", name: "Light Green 3" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [118, 108, 43], id: "C-110", name: "Light Green 4" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [121, 95, 38], id: "C-111", name: "Light Green 5" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [186, 184, 162], id: "C-112", name: "Light Green 6" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [114, 140, 84], id: "C-113", name: "Light Green 7" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [126, 124, 68], id: "C-114", name: "Light Green 8" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [100, 105, 46], id: "C-115", name: "Light Green 9" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [78, 88, 44], id: "C-116", name: "Light Green 10" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [74, 94, 45], id: "C-117", name: "Green 1" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [113, 196, 82], id: "C-118", name: "Green 2" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [102, 204, 153], id: "C-119", name: "Green 3" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [86, 154, 131], id: "C-120", name: "Green 4" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [20, 194, 91], id: "C-121", name: "Green 5" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [24, 168, 24], id: "C-122", name: "Green 6" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [4, 85, 46], id: "C-123", name: "Green 7" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [19, 107, 90], id: "C-124", name: "Green 8" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [5, 70, 65], id: "C-125", name: "Green 9" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [217, 182, 214], id: "C-126", name: "Pink 1" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [173, 98, 164], id: "C-127", name: "Pink 2" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [230, 140, 163], id: "C-128", name: "Pink 3" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [222, 84, 121], id: "C-129", name: "Pink 4" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [158, 130, 186], id: "C-130", name: "Pink 5" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [232, 65, 107], id: "C-131", name: "Pink 6" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [183, 56, 143], id: "C-132", name: "Purple 1" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [88, 31, 126], id: "C-133", name: "Purple 2" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [140, 163, 212], id: "C-134", name: "Light Blue 4" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [154, 154, 204], id: "C-135", name: "Light Blue 5" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [89, 129, 193], id: "C-136", name: "Light Blue 6" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [65, 102, 176], id: "C-137", name: "Light Blue 7" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [71, 95, 171], id: "C-138", name: "Light Blue 8" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [55, 69, 147], id: "C-139", name: "Light Blue 9" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [61, 86, 165], id: "C-140", name: "Blue 8" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [41, 66, 153], id: "C-141", name: "Blue 9" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [37, 38, 138], id: "C-142", name: "Blue 10" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [26, 47, 111], id: "C-143", name: "Blue 11" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [211, 201, 93], id: "C-144", name: "Yellow Green" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [81, 9, 24], id: "C-145", name: "Red 1" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [100, 179, 158], id: "C-146", name: "Green 10" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [99, 67, 56], id: "C-147", name: "Brown 1" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [237, 211, 158], id: "C-148", name: "Light Yellow 1" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [105, 99, 171], id: "C-149", name: "Light Purple 1" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [43, 63, 31], id: "C-150", name: "Dark Green 1" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [151, 145, 197], id: "C-151", name: "Light Purple 2" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [184, 189, 224], id: "C-152", name: "Light Purple 3" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [249, 200, 152], id: "C-153", name: "Light Brown 2" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [195, 144, 105], id: "C-154", name: "Light Brown 4" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [68, 80, 91], id: "C-155", name: "Gray 5" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [62, 73, 85], id: "C-156", name: "Gray 6" },
{ two:true,five:false, twoBasic: false, fiveBasic: false, rgb: [32, 40, 48], id: "C-157", name: "Gray 7" },
{ two:false,five:true, twoBasic: false, fiveBasic: true, rgb: [255, 255, 255], id: "S-1", name: "White" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [255, 163, 139], id: "S-2", name: "Burning Sand" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [246, 176, 76], id: "S-3", name: "Tangerine" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [234, 170, 0], id: "S-4", name: "Orange" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [225, 6, 0], id: "S-5", name: "Tall Poppy" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [236, 134, 208], id: "S-6", name: "Raspberry Pink" },
{ two:false,five:true, twoBasic: false, fiveBasic: true, rgb: [155, 155, 155], id: "S-7", name: "Gray 2" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [36, 222, 91], id: "S-8", name: "Emerald" },
{ two:false,five:true, twoBasic: false, fiveBasic: true, rgb: [0, 104, 94], id: "S-9", name: "Dark Green" },
{ two:false,five:true, twoBasic: false, fiveBasic: true, rgb: [65, 182, 230], id: "S-1O", name: "Baby Blue" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [0, 51, 153], id: "S-11", name: "Dark Blue" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [160, 94, 191], id: "S-12", name: "Pastel Lavender" },
{ two:false,five:true, twoBasic: false, fiveBasic: true, rgb: [0, 0, 0], id: "S-13", name: "Black" },
{ two:false,five:true, twoBasic: false, fiveBasic: true, rgb: [250, 224, 83], id: "S-14", name: "Sandstone" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [122, 62, 44], id: "S-15", name: "Redwood" },
{ two:false,five:true, twoBasic: false, fiveBasic: true, rgb: [92, 71, 56], id: "S-16", name: "Brown" },
{ two:false,five:true, twoBasic: false, fiveBasic: true, rgb: [123, 77, 53], id: "S-17", name: "Light Brown" },
{ two:false,five:true, twoBasic: false, fiveBasic: true, rgb: [204, 153, 102], id: "S-18", name: "" },
{ two:false,five:true, twoBasic: false, fiveBasic: true, rgb: [252, 191, 169], id: "S-19", name: "Bubble Gum" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [36, 158, 107], id: "S-20", name: "Green" },
{ two:false,five:true, twoBasic: false, fiveBasic: true, rgb: [135, 216, 57], id: "S-21", name: "Pastel Green" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [51, 0, 114], id: "S-22", name: "Purple" },
{ two:false,five:true, twoBasic: false, fiveBasic: true, rgb: [100, 53, 155], id: "S-23", name: "Royal Purple" },
{ two:false,five:true, twoBasic: false, fiveBasic: true, rgb: [20, 123, 209], id: "S-24", name: "True Blue" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [255, 52, 179], id: "S-25", name: "Hot Pink" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [219, 33, 82], id: "S-26", name: "Magenta" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [255, 209, 0], id: "S-27", name: "Yellow" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [234, 184, 228], id: "S-28", name: "Lily Pink" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [246, 235, 97], id: "S-29", name: "" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [153, 214, 234], id: "S-30", name: "" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [158, 229, 176], id: "S-31", name: "" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [255, 231, 128], id: "S-32", name: "Beeswax" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [197, 180, 227], id: "S-33", name: "Maverick" },
{ two:false,five:true, twoBasic: false, fiveBasic: true, rgb: [186, 12, 47], id: "S-34", name: "Red" },
{ two:false,five:true, twoBasic: false, fiveBasic: true, rgb: [247, 206, 215], id: "S-35", name: "" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [201, 128, 158], id: "S-36", name: "Old Pink" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [113, 216, 191], id: "S-37", name: "Blue Green" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [171, 37, 86], id: "S-38", name: "Burgundy" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [247, 139, 0], id: "S-39", name: "Yellow Orange" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [241, 167, 220], id: "S-40", name: "Carnation Pink" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [154, 85, 22], id: "S-41", name: "Copper" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [160, 159, 157], id: "S-42", name: "Silver" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [118, 119, 119], id: "S-43", name: "Gray 3" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [170, 220, 235], id: "S-44", name: "Sky Blue" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [0, 178, 169], id: "S-45", name: "Medium Turquoise" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [115, 211, 60], id: "S-46", name: "Bright Green" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [180, 126, 0], id: "S-47", name: "Marigold" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [255, 199, 44], id: "S-48", name: "Corn" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [114, 25, 95], id: "S-49", name: "Mulberry Wood" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [250, 170, 114], id: "S-50", name: "" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [252, 251, 205], id: "S-51", name: "Spring Sun" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [242, 240, 161], id: "S-52", name: "Picasso" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [105, 179, 231], id: "S-53", name: "Blue Enchantress" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [0, 144, 218], id: "S-54", name: "Light Blue" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [173, 220, 145], id: "S-55", name: "Pistachio" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [255, 106, 19], id: "S-56", name: "Outrageous Orange" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [164, 73, 61], id: "S-57", name: "Buccaneer" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [165, 0, 52], id: "S-58", name: "Paprika" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [74, 31, 135], id: "S-59", name: "Butterfly Bush" },
{ two:false,five:true, twoBasic: false, fiveBasic: true, rgb: [219, 33, 82], id: "S-60", name: "Lavander" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [206, 220, 0], id: "S-61", name: "Key Lemon Pie" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [0, 124, 88], id: "S-62", name: "" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [88, 87, 53], id: "S-63", name: "Metallic Gold" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [5, 8, 73], id: "S-64", name: "Black Rock" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [243, 234, 93], id: "S-65", name: "" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [244, 99, 58], id: "S-66", name: "" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [243, 207, 179], id: "S-67", name: "Vainilla" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [225, 192, 120], id: "S-68", name: "Tan" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [35, 40, 43], id: "S-69", name: "Mine Shaft" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [155, 188, 17], id: "S-70", name: "Drark Algae" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [0, 133, 43], id: "S-71", name: "Jade Green" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [89, 213, 216], id: "S-72", name: "Light Sea Blue" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [72, 169, 197], id: "S-73", name: "" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [0, 174, 214], id: "S-74", name: "" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [0, 133, 173], id: "S-75", name: "Dark Steel Blue" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [0, 174, 199], id: "S-76", name: "" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [239, 239, 239], id: "S-77", name: "Ghost White" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [209, 209, 209], id: "S-78", name: "Ash Gray" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [187, 188, 188], id: "S-79", name: "Gray 1" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [153, 155, 48], id: "S-80", name: "Dark Olive" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [205, 178, 119], id: "S-81", name: "Deer" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [181, 129, 80], id: "S-82", name: "" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [184, 97, 37], id: "S-83", name: "Siena" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [170, 87, 97], id: "S-84", name: "Deep Chestnut" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [92, 19, 27], id: "S-85", name: "Red Wine" },
{ two:false,five:true, twoBasic: false, fiveBasic: true, rgb: [255, 103, 31], id: "S-86", name: "Goldenrod" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [255, 109, 106], id: "S-87", name: "Goldenrod" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [218, 24, 132], id: "S-88", name: "" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [72, 73, 85], id: "S-89", name: "Gray 4" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [255, 197, 110], id: "S-90", name: "" },
{ two:false,five:true, twoBasic: false, fiveBasic: false, rgb: [24, 48, 40], id: "S-91", name: "Brunswick Green" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [222, 185, 71], id: "S-92", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [218, 182, 152], id: "S-93", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [244, 169, 153], id: "S-94", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [238, 125, 103], id: "S-95", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [240, 134, 97], id: "S-96", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [212, 114, 42], id: "S-97", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [100, 172, 223], id: "S-98", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [100, 194, 220], id: "S-99", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [79, 159, 179], id: "S-100", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [49, 150, 221], id: "S-101", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [27, 108, 182], id: "S-102", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [8, 57, 128], id: "S-103", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [10, 102, 139], id: "S-104", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [8, 91, 110], id: "S-105", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [0, 78, 120], id: "S-106", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [0, 85, 116], id: "S-107", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [204, 190, 128], id: "S-108", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [164, 147, 80], id: "S-109", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [158, 136, 60], id: "S-110", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [118, 108, 43], id: "S-111", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [121, 95, 38], id: "S-112", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [186, 184, 162], id: "S-113", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [114, 140, 84], id: "S-114", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [126, 124, 68], id: "S-115", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [100, 105, 46], id: "S-116", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [78, 88, 44], id: "S-117", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [74, 94, 45], id: "S-118", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [113, 196, 82], id: "S-119", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [102, 204, 153], id: "S-120", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [86, 154, 131], id: "S-121", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [20, 194, 91], id: "S-122", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [24, 168, 24], id: "S-123", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [4, 85, 46], id: "S-124", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [19, 107, 90], id: "S-125", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [5, 70, 65], id: "S-126", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [217, 182, 214], id: "S-127", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [173, 98, 164], id: "S-128", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [230, 140, 163], id: "S-129", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [222, 84, 121], id: "S-130", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [158, 130, 186], id: "S-131", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [232, 65, 107], id: "S-132", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [183, 56, 143], id: "S-133", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [88, 31, 126], id: "S-134", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [140, 163, 212], id: "S-135", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [154, 154, 204], id: "S-136", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [89, 129, 193], id: "S-137", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [65, 102, 176], id: "S-138", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [71, 95, 171], id: "S-139", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [55, 69, 147], id: "S-140", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [61, 86, 165], id: "S-141", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [41, 66, 135], id: "S-142", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [37, 38, 138], id: "S-143", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [26, 47, 111], id: "S-144", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [211, 201, 93], id: "S-145", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [81, 9, 24], id: "S-146", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [100, 179, 158], id: "S-147", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [99, 67, 56], id: "S-148", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [237, 211, 158], id: "S-149", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [105, 99, 171], id: "S-150", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [43, 63, 31], id: "S-151", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [151, 145, 197], id: "S-152", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [184, 189, 224], id: "S-153", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [249, 200, 152], id: "S-154", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [195, 144, 105], id: "S-155", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [68, 80, 91], id: "S-156", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [62, 73, 85], id: "S-157", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [32, 40, 48], id: "S-158", name: "" },
{ two:false,five:false, twoBasic: false, fiveBasic: false, rgb: [136, 139, 141], id: "S-159", name: "" },
]